export type { Availability } from "@scripts/catalog-common";
import type { Availability } from "@scripts/catalog-common";

export interface GearTemplate {
  templateId: string;
  name: string;
  description: string;
  type: string;
  cost?: number;
  availability?: Availability;
}

function t(
  templateId: string,
  name: string,
  type: string,
  description: string,
  opts?: { cost?: number; availability?: Availability },
): GearTemplate {
  return {
    templateId,
    name,
    description,
    type,
    cost: opts?.cost,
    availability: opts?.availability,
  };
}

export const GEAR_CATALOG: Record<string, GearTemplate> = {
  // === Fashion ===
  pants: t(
    "pants",
    "Pants",
    "fashion",
    "Basic streetwear pants. Multiply cost by style: Generic Chic 1x, Leisurewear 2x, Businesswear 3x, High Fashion 4x, Urban Flash 2x.",
    { cost: 20 },
  ),
  top: t(
    "top",
    "Top",
    "fashion",
    "Basic streetwear top. Multiply cost by style: Generic Chic 1x, Leisurewear 2x, Businesswear 3x, High Fashion 4x, Urban Flash 2x.",
    { cost: 15 },
  ),
  jacket: t(
    "jacket",
    "Jacket",
    "fashion",
    "Basic streetwear jacket. Multiply cost by style: Generic Chic 1x, Leisurewear 2x, Businesswear 3x, High Fashion 4x, Urban Flash 2x.",
    { cost: 35 },
  ),
  footwear: t(
    "footwear",
    "Footwear",
    "fashion",
    "Boots, shoes, etc. Multiply cost by style: Generic Chic 1x, Leisurewear 2x, Businesswear 3x, High Fashion 4x, Urban Flash 2x.",
    { cost: 25 },
  ),
  jewelry: t(
    "jewelry",
    "Jewelry",
    "fashion",
    "Decorative accessories. 10\u2013100eb depending on quality.",
    { cost: 10 },
  ),
  mirrorshades: t(
    "mirrorshades",
    "Mirrorshades",
    "fashion",
    "Reflective sunglasses. 5\u201350eb depending on style.",
    { cost: 5 },
  ),
  contact_lenses: t(
    "contact_lenses",
    "Contact Lenses",
    "fashion",
    "Cosmetic or corrective contact lenses.",
    { cost: 100 },
  ),
  glasses: t(
    "glasses",
    "Glasses",
    "fashion",
    "Corrective or fashion eyewear. Multiply cost by style: Generic Chic 1x, Leisurewear 2x, Businesswear 3x, High Fashion 4x, Urban Flash 2x.",
    { cost: 50 },
  ),

  // === Tools ===
  techscanner: t(
    "techscanner",
    "Techscanner",
    "tools",
    "Small handheld microcomp with I/O connectors and probes. Runs diagnostic programs, identifies malfunctioning components, displays internal schematics on a small screen.",
    { cost: 600 },
  ),
  cutting_torch: t(
    "cutting_torch",
    "Cutting Torch",
    "tools",
    "Common oxy/acetalyne type, about a foot long. More powerful models available; up to thermite lances at 5x\u201315x cost.",
    { cost: 40 },
  ),
  tech_tool_kit: t(
    "tech_tool_kit",
    "Tech Tool Kit",
    "tools",
    'Mixed kit of tools for repair of mechanical items, usually in a 4"x16"x2" case.',
    { cost: 100 },
  ),
  b_and_e_tools: t(
    "b_and_e_tools",
    "B & E Tools",
    "tools",
    "Breaking and entering toolkit.",
    { cost: 120 },
  ),
  electronics_toolkit: t(
    "electronics_toolkit",
    "Electronics Toolkit",
    "tools",
    "Kit for repair and modification of electronic devices.",
    { cost: 100 },
  ),
  protective_goggles: t(
    "protective_goggles",
    "Protective Goggles",
    "tools",
    "Protective eyewear for welding, metal machining, chemical mixing, etc.",
    { cost: 20 },
  ),
  flashtube: t(
    "flashtube",
    "Flashtube",
    "tools",
    "Flashlight. Beam range 100\u2013120'. Smaller pocket lights (1/4 range) cost half.",
    { cost: 2 },
  ),
  glowstik: t(
    "glowstik",
    "Glowstik",
    "tools",
    'Chemlight in a 6" plastic tube. Shake or break to activate. Soft light lasts up to 6 hours. Comes in green, blue, red.',
    { cost: 1 },
  ),
  flash_paint: t(
    "flash_paint",
    "Flash Paint",
    "tools",
    "Fluorescent paint that gives off soft light equal to a Glowstik. Lasts up to 4 hours. Price per point.",
    { cost: 10 },
  ),
  flash_tape: t(
    "flash_tape",
    "Flash Tape",
    "tools",
    "Same as Flash Paint but on tape. Lasts 6 hours, comes in variety of widths. Price per foot.",
    { cost: 10 },
  ),
  rope: t(
    "rope",
    "Rope",
    "tools",
    "Braided synthetics in a variety of thicknesses and weights. Can hold up to 1,000 lbs. Price per foot.",
    { cost: 2 },
  ),
  breathing_mask: t(
    "breathing_mask",
    "Breathing Mask",
    "tools",
    "Common painter's style mask; nose and mouth coverage, with two replaceable filters (1eb per 10 pack). Good for keeping out the smog.",
    { cost: 30 },
  ),

  // === Personal Electronics ===
  holo_generator: t(
    "holo_generator",
    "Holo Generator",
    "personal electronics",
    'Small box (approx. 4"x2"x6") that projects a holographic picture from a replaceable chip. Compatible with chips from most digital cameras. Can be linked with a digital Recorder/Player.',
    { cost: 500 },
  ),
  video_board: t(
    "video_board",
    "Video Board",
    "personal electronics",
    "Monitor using flat-LCD technology. No thicker than an inch. All types have input plugs for use as readout for other electronics. Large ones (20'x100') are used as advertising signs. Price per sq ft.",
    { cost: 100 },
  ),
  data_chip: t(
    "data_chip",
    "Data Chip",
    "personal electronics",
    "The storage medium of the future. Plastic-cased, comes in buttons, flat squares, and triangular slivers. All shapes readable by all recording media via adapter plugs.",
    { cost: 10 },
  ),
  logcompass: t(
    "logcompass",
    "Logcompass",
    "personal electronics",
    "Programmable inertial compass that keeps track of your changes in direction from a fixed bearing or point.",
    { cost: 50 },
  ),
  digital_recorder: t(
    "digital_recorder",
    "Digital Recorder",
    "personal electronics",
    "Audio recording device using datachip technology. Most are the size of two paperback books stacked flat. Some are smaller than a pack of cards.",
    { cost: 300 },
  ),
  digital_camera: t(
    "digital_camera",
    "Digital Camera",
    "personal electronics",
    "Still images are 'digitized' onto a chip cartridge. About the size of a pack of cigarettes.",
    { cost: 150 },
  ),
  videocam: t(
    "videocam",
    "VideoCam",
    "personal electronics",
    "Can be mounted on a headset, shoulder clamp, or hand-held. Price varies by size, image quality, and recording duration.",
    { cost: 800 },
  ),
  video_audio_tape_player: t(
    "video_audio_tape_player",
    "Video/Audio Tape Player",
    "personal electronics",
    "Plays videocam tape-paks, along with many older-style audio tapes.",
    { cost: 40 },
  ),
  video_tape: t(
    "video_tape",
    "Video Tape",
    "personal electronics",
    "High density digital media capable of handling both audio and visual images.",
    { cost: 4 },
  ),
  pocket_tv: t(
    "pocket_tv",
    "Pocket TV",
    "personal electronics",
    'Flat-scan screen in a package 5"x5"x3/4" or smaller. Picks up VHF, UHF stations.',
    { cost: 80 },
  ),
  digital_chip_player: t(
    "digital_chip_player",
    "Digital Chip Player",
    "personal electronics",
    "Plays audio- and video-recorded chips. Must plug into a video board to play the video track.",
    { cost: 150 },
  ),
  digital_music_chip: t(
    "digital_music_chip",
    "Digital Music Chip",
    "personal electronics",
    "1 to 6 pop album favorites slapped into semiconductors and plastic. Also available in read-write format.",
    { cost: 20 },
  ),
  electric_guitar: t(
    "electric_guitar",
    "Electric Guitar",
    "personal electronics",
    "No longer the classic 'axe' \u2014 now lighter, more flexible, and sometimes not even in a recognizable shape. 100\u2013500eb.",
    { cost: 100 },
  ),
  electronic_keyboard: t(
    "electronic_keyboard",
    "Electronic Keyboard",
    "personal electronics",
    "Little changed from the present, except in size and power. 200\u2013900eb.",
    { cost: 200 },
  ),
  drum_synthesizer: t(
    "drum_synthesizer",
    "Drum Synthesizer",
    "personal electronics",
    "Common 'new-wave' music equipment; percussion pads and a sound box. Fits in a couple of suitcases. 200\u2013800eb.",
    { cost: 200 },
  ),
  amplifier: t(
    "amplifier",
    "Amplifier",
    "personal electronics",
    "For more on instruments of the 2010s\u201320s, check the supplement Rockerboy. 500\u20131000eb.",
    { cost: 500 },
  ),

  // === Data Systems ===
  laptop_computer: t(
    "laptop_computer",
    "Laptop Computer",
    "data systems",
    "The common portable, with internal hard drive, video board (detachable), and slots for data/programming chips. Cannot be used for Netrunning.",
    { cost: 900 },
  ),
  pocket_computer: t(
    "pocket_computer",
    "Pocket Computer",
    "data systems",
    'The classic 6"x3"x1/2" programmable calculator with keyboard and chip slots, up to 100 pages of alphanumeric memory.',
    { cost: 100 },
  ),
  interface_cables: t(
    "interface_cables",
    "Interface Cables",
    "data systems",
    "Typical plug-ended splicing cables from a cyber-operated machine to a person's interface sockets. 20\u201330eb.",
    { cost: 20 },
  ),
  low_impedance_cables: t(
    "low_impedance_cables",
    "Low Impedance Cables",
    "data systems",
    "Special low-resistance/interference cables for improved data transfer; +1 bonus on interfacing tasks such as controlling cybervehicles or Netrunning.",
    { cost: 60 },
  ),
  trode_set: t(
    "trode_set",
    "'Trode Set",
    "data systems",
    "A low efficiency headset for 'piggybacking' in the Net. \u22122 to Interface skill.",
    { cost: 20 },
  ),
  keyboard: t(
    "keyboard",
    "Keyboard",
    "data systems",
    "Can be accessorized to your cybermodem or other electronic equipment.",
    { cost: 100 },
  ),
  terminal: t(
    "terminal",
    "Terminal",
    "data systems",
    "Computer workstation with keyboard, video board, and I/O connectors. Can Netrun (runner is immune to most Black software) but very slow (\u22125 to Interface Skills). Operators known as 'net-tortoises'.",
    { cost: 400 },
  ),

  // === Communications ===
  mastoid_commo: t(
    "mastoid_commo",
    "Mastoid Commo",
    "communications",
    "Radio transceiver glued to the jaw and temple; send via subvocalization, receive with soundless vibrations. Range 10 miles.",
    { cost: 100 },
  ),
  pocket_commo: t(
    "pocket_commo",
    "Pocket Commo",
    "communications",
    "A typical small walkie-talkie. Range 10 miles.",
    { cost: 50 },
  ),
  cellular_phone: t(
    "cellular_phone",
    "Cellular Phone",
    "communications",
    "Communication on the move, anywhere within reach of a radiotelephone transceiver network. 100eb/month service charge.",
    { cost: 400 },
  ),
  mini_cell_phone: t(
    "mini_cell_phone",
    "MiniCell Phone",
    "communications",
    "Fits in a cigarette pack.",
    { cost: 800 },
  ),

  // === Surveillance ===
  binoglasses: t(
    "binoglasses",
    "Binoglasses",
    "surveillance",
    "High-tech vision aids combining binocular effects with a laser rangefinder, sometimes IR lenses. More expensive versions have a built-in camera.",
    { cost: 200 },
  ),
  binoculars: t(
    "binoculars",
    "Binoculars",
    "surveillance",
    "Standard binoculars.",
    { cost: 20 },
  ),
  lb_goggles: t(
    "lb_goggles",
    "Light Booster Goggles",
    "surveillance",
    "Light intensification goggles boosting ambient light for night vision via 'Starlite' technology. Can be overwhelmed by sudden light increase. With tuning (DIFFICULT), can also detect active IR beams.",
    { cost: 200 },
  ),
  ir_goggles: t(
    "ir_goggles",
    "IR Goggles",
    "surveillance",
    "Pick up hazy, background infrared sources. Normally used with an active IR source for invisible illumination.",
    { cost: 250 },
  ),
  ir_flash: t(
    "ir_flash",
    "IR Flash",
    "surveillance",
    "UV flash; also useable with the proper cyberoptic.",
    { cost: 50 },
  ),

  // === Security ===
  keylock: t(
    "keylock",
    "Keylock",
    "security",
    "Mechanical lock. Difficulty by level: Low 15, Medium 20, High 25, Maximum 30. Price per level.",
    { cost: 20 },
  ),
  cardlock: t(
    "cardlock",
    "Cardlock",
    "security",
    "Electronic lock using magnetically-coded card. Difficulty by level: Low 15, Medium 20, High 25, Maximum 30. Price per level.",
    { cost: 100 },
  ),
  vocolock: t(
    "vocolock",
    "Vocolock",
    "security",
    "Voice-recognition lock. Difficulty by level: Low 15, Medium 20, High 25, Maximum 30. Price per level.",
    { cost: 200 },
  ),
  line_tap: t(
    "line_tap",
    "Line Tap",
    "security",
    "Picks up voice or data from a telecom line, then records or transmits them. Works up to a foot away; can be remote controlled. Cannot be used on post-2008 fiber optic systems.",
    { cost: 200 },
  ),
  code_decryptor: t(
    "code_decryptor",
    "CodeDecryptor",
    "security",
    "Cardlock Decryptor. Probe inserted into a card lock instead of the normal card. Adds +5 to TECH+Electronic Security+1D10 check against the lock.",
    { cost: 500 },
  ),
  voc_decryptor: t(
    "voc_decryptor",
    "VocDecryptor",
    "security",
    "A vocal modulator for penetrating vocolocks.",
    { cost: 1000 },
  ),
  security_scanner: t(
    "security_scanner",
    "Security Scanner",
    "security",
    "Searches out electromagnetic fields generated by alarm systems (75% chance of detection). A TECH or INT roll may be needed to identify the alarm type.",
    { cost: 1500 },
  ),
  poison_sniffer: t(
    "poison_sniffer",
    "Poison Sniffer",
    "security",
    "Can check air or liquid for a specific poison, or alert you to foreign substances. 85% accuracy.",
    { cost: 1500 },
  ),
  jamming_transmitter: t(
    "jamming_transmitter",
    "Jamming Transmitter",
    "security",
    "Usually 2\u20133 large cases, can fill an entire van. Jams electromagnetic transmissions in a 1000 ft area (includes cellular phones and some cyberware).",
    { cost: 500 },
  ),
  scanner_plate: t(
    "scanner_plate",
    "Scanner Plate",
    "security",
    "Palmprint lock reader. Can be attached to any Card or Vocolock to add an extra layer of security.",
    { cost: 500 },
  ),
  movement_sensor: t(
    "movement_sensor",
    "Movement Sensor",
    "security",
    "Typical alarm system covering seismic, sonar, and fixed IR or visible light networks. 95% reliability. About the size of a pack of cigarettes.",
    { cost: 40 },
  ),
  passcard: t(
    "passcard",
    "Passcard",
    "security",
    "The most common unlocking device for a cardlock.",
    { cost: 10 },
  ),
  tracking_device: t(
    "tracking_device",
    "Tracking Device",
    "security",
    "Hand held or suitcased equipment for detecting/following tracer buttons. Range 1 mile.",
    { cost: 1000 },
  ),
  tracer_button: t(
    "tracer_button",
    "Tracer Button",
    "security",
    "Any size from matchbook to pin. Uses radioactivity or radio transmission to pinpoint location. Some can be turned on/off remotely. Usually bought in sets of 6.",
    { cost: 50 },
  ),
  remote_sensors: t(
    "remote_sensors",
    "Remote Sensors",
    "security",
    "Remote monitoring sensor package.",
    { cost: 700 },
  ),
  plaskuffs: t(
    "plaskuffs",
    "PlasKuffs",
    "security",
    "Handcuffs. Stronger than old-style (NEARLY IMPOSSIBLE to break) due to new alloys. Often (50%) opened with a form of cardlock.",
    { cost: 100 },
  ),
  stripwire_binders: t(
    "stripwire_binders",
    "Stripwire Binders",
    "security",
    "One-use plastic locking strips for temporary cuffs and leg ties (VERY DIFFICULT to break). Ceramic fibers resist cutting, guaranteed fireproof. Box of 12.",
    { cost: 5 },
  ),

  // === Medical ===
  dermal_stapler: t(
    "dermal_stapler",
    "Dermal Stapler",
    "medical",
    "Automatically pulls wound sides together and sutures with staples of compressed organic material that dissolves after time.",
    { cost: 1000 },
  ),
  spray_skin: t(
    "spray_skin",
    "Spray Skin",
    "medical",
    "Putty-like spray gel for severe abrasions. Antiseptic, sterile, air permeable. Flakes off in about two weeks. Price per can.",
    { cost: 50 },
  ),
  slap_patch: t(
    "slap_patch",
    "Slap Patch",
    "medical",
    "A small pad applied to the skin; medicine is absorbed in steady doses. See Trauma Team section for drugs and prices.",
  ),
  airhypo: t(
    "airhypo",
    "Airhypo",
    "medical",
    "The 'Bones McCoy' \u2014 uses a quick burst of compressed air to force a liquid drug through the skin. See Trauma Team section for drugs and prices.",
    { cost: 100 },
  ),
  cryotank: t(
    "cryotank",
    "Cryotank",
    "medical",
    "Advanced refrigeration tank; cools a body to preservation levels while life-support maintains blood/oxygen flow. Keeps a dying body in relative stasis.",
    { cost: 100000 },
  ),
  medkit: t(
    "medkit",
    "Medkit",
    "medical",
    "Standard doctor's or military corpsman's bag. Antidotes, dressings, drugs, applicators, medicines, examining instruments (probes, depressors, ocular light, stethoscope).",
    { cost: 50 },
  ),
  surgical_kit: t(
    "surgical_kit",
    "Surgical Kit",
    "medical",
    "Full set of surgeon's tools (scalpel, retractor, probe, clamp, tweezer, etc.) and chemicals/equipment for maintaining a sterile operating field.",
    { cost: 400 },
  ),
  first_aid_kit: t(
    "first_aid_kit",
    "First Aid Kit",
    "medical",
    "The common household medic's box. Bandages, antiseptics, and a simple painkiller.",
    { cost: 10 },
  ),
  medscanner: t(
    "medscanner",
    "Medscanner",
    "medical",
    "Readouts for body temperature, heartrate, blood pressure, respiration, blood sugar. Chipped database adds +2 to Diagnose Skill.",
    { cost: 300 },
  ),
  drug_analyser: t(
    "drug_analyser",
    "Drug Analyser",
    "medical",
    "Ranging from book to briefcase in size. Determines purity of a known drug, or identifies molecular makeup and possible effects of an unknown substance.",
    { cost: 75 },
  ),

  // === Furnishings ===
  nylon_carrybag: t(
    "nylon_carrybag",
    "Nylon Carrybag",
    "furnishings",
    "The athletic bag/kitbag of the 2000's, with a variety of logos. Sizes vary.",
    { cost: 5 },
  ),
  sleeping_bag: t(
    "sleeping_bag",
    "Sleeping Bag",
    "furnishings",
    'Lighter weight, handles temps down to -100F. Compresses to 12"x6"x4".',
    { cost: 25 },
  ),
  inflatable_bed: t(
    "inflatable_bed",
    "Inflatable Bed",
    "furnishings",
    'Self-inflating, highly-compressed mattress package. About 6"x2"x4" folded.',
    { cost: 25 },
  ),
  futon: t(
    "futon",
    "Futon",
    "furnishings",
    "Portable folding bed and pad; of Japanese origin.",
    { cost: 90 },
  ),
  apartment_cube: t(
    "apartment_cube",
    "Apartment Cube",
    "furnishings",
    "10'x10'x8' living module with bed, closet, small stove, fridge, TV, entertainment center, chairs, fold-down desk, removable table. All hidden in flush wall recesses. Rolls into place.",
    { cost: 5000 },
  ),
  lamp: t(
    "lamp",
    "Lamp",
    "furnishings",
    "Comes in an infinity of shapes and colors.",
    { cost: 20 },
  ),
  cleaning_bot: t(
    "cleaning_bot",
    "Cleaning Bot",
    "furnishings",
    "Small preprogrammed robotic cleaning device. About the size of a portable cannister vacuum. Not too smart.",
    { cost: 1000 },
  ),
  vocal_switcher: t(
    "vocal_switcher",
    "Vocal Switcher System",
    "furnishings",
    "Voice-activated controls for lights and appliances.",
    { cost: 100 },
  ),

  // === Vehicles ===
  scooter: t(
    "scooter",
    "Scooter",
    "vehicles",
    "Electrically powered, top speed ~50 mph. About 6 hours travel per fastcharge (5 min at any service station).",
    { cost: 500 },
  ),
  motorcycle: t(
    "motorcycle",
    "Motorcycle",
    "vehicles",
    "Recumbent designs with plastic fairings. Electric: 65mph, 8 hrs/charge. CHOOH\u00B2: top end 140mph, 4 gallon tank.",
    { cost: 1500 },
  ),
  citycar: t(
    "citycar",
    "CityCar",
    "vehicles",
    "One man (two in a pinch), three-wheeler. Top speed ~40mph, 4 hrs/fastcharge. Can be rented (2eb/mile) from kiosks.",
    { cost: 2000 },
  ),
  small_subcompact: t(
    "small_subcompact",
    "Small Subcompact",
    "vehicles",
    "Methanol or CHOOH\u00B2 powered, ~90mph, ten gallon tank, seats four.",
    { cost: 6000 },
  ),
  medium_sedan: t(
    "medium_sedan",
    "Medium Sedan",
    "vehicles",
    "Methanol or CHOOH\u00B2 powered, ~90mph, fifteen gallon tank, seats four.",
    { cost: 10000 },
  ),
  sportscar: t(
    "sportscar",
    "Sportscar",
    "vehicles",
    "Almost always CHOOH\u00B2 powered. Top speed ~210mph, ten gallon tank. Seats 2.",
    { cost: 20000 },
  ),
  luxury_sedan: t(
    "luxury_sedan",
    "Luxury Sedan",
    "vehicles",
    "Methanol or CHOOH\u00B2 powered, ~90mph, twenty gallon tank, seats six.",
    { cost: 40000 },
  ),
};

export { AVAILABILITY_LABELS } from "@scripts/catalog-common";
