export type { WearResult } from "./actions";
export {
  acquireArmor,
  addCustomArmor,
  checkLayerConstraints,
  damageArmor,
  discardArmor,
  removeCustomArmor,
  renameCustomArmor,
  setArmorSP,
  toggleArmor,
  unwearAll,
  updateCustomArmor,
  wearArmor,
} from "./actions";
export {
  getImplantLayer,
  getImplantTemplates,
  getInstalledSkinweave,
  getSkinweaveLevel,
  installImplant,
  installSkinweave,
  isImplantInstalled,
  repairImplant,
  uninstallImplant,
  uninstallSkinweave,
} from "./implants";
export type {
  ArmorInstance,
  ArmorLayer,
  ArmorPiece,
  ArmorTemplate,
  BodyPartName,
  CustomArmorDef,
  CustomArmorState,
  OwnedArmorState,
} from "./state";
export {
  $customArmorList,
  $customArmorTemplates,
  $encumbrance,
  $ownedArmor,
  ARMOR_CATALOG,
  getAllOwnedArmor,
  getArmorPiece,
  getBodyPartLayers,
  getImplantedArmor,
  getImplantsForPart,
  getInstalledImplants,
  getTemplate,
  IMPLANT_TEMPLATES,
  isCustomArmor,
  isImplant,
  isSkinweave,
  resolveTemplate,
} from "./state";
