export type { Availability } from "@scripts/catalog-common";
import type { Availability } from "@scripts/catalog-common";

// --- Types ---

export type WeaponType = "P" | "SMG" | "RIF" | "SHT" | "HVY" | "EX" | "melee";

export type Concealability = "P" | "J" | "L" | "N";

export type Reliability = "VR" | "ST" | "UR";

export interface WeaponTemplate {
  templateId: string;
  name: string;
  type: WeaponType;
  skill: string;
  wa: number;
  concealability: Concealability;
  availability: Availability;
  damage: string;
  ammo: string;
  shots: number;
  rof: number;
  reliability: Reliability;
  range: number;
  cost: number;
  description: string;
  melee: boolean;
  smartchipped: boolean;
}

// --- Labels ---

export const WEAPON_TYPE_LABELS: Record<WeaponType, string> = {
  P: "Pistol",
  SMG: "SMG",
  RIF: "Rifle",
  SHT: "Shotgun",
  HVY: "Heavy",
  EX: "Exotic",
  melee: "Melee",
};

export const CONCEALABILITY_LABELS: Record<Concealability, string> = {
  P: "Pocket",
  J: "Jacket",
  L: "Long Coat",
  N: "Can't Hide",
};

export const RELIABILITY_LABELS: Record<Reliability, string> = {
  VR: "Very Reliable",
  ST: "Standard",
  UR: "Unreliable",
};

// --- Helpers ---

export function skillForType(type: WeaponType): string {
  switch (type) {
    case "P":
      return "Handgun";
    case "SMG":
      return "Submachinegun";
    case "RIF":
      return "Rifle";
    case "SHT":
      return "Rifle";
    case "HVY":
      return "Heavy Weapons";
    case "EX":
      return "Archery"; // close enough for now, we'll pass custom skill for exotics that use other skills
    case "melee":
      return "Melee";
  }
}

/**
 * Caliber → default damage lookup.
 * Used to auto-fill damage when caliber is entered on custom weapons.
 * NOTE: When ammo becomes its own item type, ammo will be the source of truth
 * for damage (and can alter it — e.g. AP rounds reduce raw damage but halve SP).
 * This lookup is a stopgap for custom weapon creation until then.
 */
export const CALIBER_DAMAGE: Record<string, string> = {
  "5mm": "1D6",
  ".25": "1D6+1",
  ".22": "1D6",
  "6mm": "1D6+1",
  "7mm": "1D6+2",
  ".38": "1D6+2",
  "9mm": "2D6+1",
  "10mm": "2D6+3",
  ".357": "3D6+1",
  ".45": "2D6+2",
  ".40": "2D6+3",
  "11mm": "3D6",
  "12mm": "4D6+1",
  ".44": "4D6",
  "5.56mm": "5D6",
  "5.7mm": "3D6",
  "7.62mm": "6D6+2",
  "7.62x39": "5D6+2",
  "30-06": "5D6+1",
  "00": "4D6",
  "20mm": "4D10 AP",
};

// Compact weapon constructor matching corebook weapon code order:
// Name • Type • WA • Concealability • Availability • Damage • Ammo • #Shots • ROF • Reliability • Range • Cost
function w(
  templateId: string,
  name: string,
  type: WeaponType,
  wa: number,
  con: Concealability,
  avail: Availability,
  damage: string,
  ammo: string,
  shots: number,
  rof: number,
  rel: Reliability,
  range: number,
  cost: number,
  description: string,
  opts?: { skill?: string },
): WeaponTemplate {
  return {
    templateId,
    name,
    type,
    skill: opts?.skill ?? skillForType(type),
    wa,
    concealability: con,
    availability: avail,
    damage,
    ammo,
    shots,
    rof,
    reliability: rel,
    range,
    cost,
    description,
    melee: type === "melee",
    smartchipped: false,
  };
}

// --- Catalog ---
// Data from Cyberpunk 2020 corebook pp. 61–66

export const WEAPON_CATALOG: Record<string, WeaponTemplate> = {
  // ═══ LIGHT AUTOPISTOLS ═══

  budgetarms_c13: w(
    "budgetarms_c13",
    "BudgetArms C-13",
    "P",
    -1,
    "P",
    "E",
    "1D6",
    "5mm",
    8,
    2,
    "ST",
    50,
    75,
    'A light duty autopistol used as a hold-out and "lady\'s gun".',
  ),
  dai_lung_cybermag: w(
    "dai_lung_cybermag",
    "Dai Lung Cybermag 15",
    "P",
    -1,
    "P",
    "C",
    "1D6+1",
    "6mm",
    10,
    2,
    "UR",
    50,
    50,
    "Cheap Hong Kong knockoff, often used by boosters and other street trash.",
  ),
  federated_x22: w(
    "federated_x22",
    "Federated Arms X-22",
    "P",
    0,
    "P",
    "E",
    "1D6+1",
    "6mm",
    10,
    2,
    "ST",
    50,
    150,
    'The ubiquitous "Polymer-one-shot" cheap plastic pistol. Available in designer colors.',
  ),

  // ═══ MEDIUM AUTOPISTOLS ═══

  militech_avenger: w(
    "militech_avenger",
    "Militech Arms Avenger",
    "P",
    0,
    "J",
    "E",
    "2D6+1",
    "9mm",
    10,
    2,
    "VR",
    50,
    250,
    "A well-made autopistol with good range and accuracy. A professional's gun.",
  ),
  dai_lung_streetmaster: w(
    "dai_lung_streetmaster",
    "Dai Lung Streetmaster",
    "P",
    0,
    "J",
    "E",
    "2D6+3",
    "10mm",
    12,
    2,
    "UR",
    50,
    250,
    "Another Dai Lung cheapie, built for the Street.",
  ),
  federated_x9: w(
    "federated_x9",
    "Federated Arms X-9mm",
    "P",
    0,
    "J",
    "E",
    "2D6+1",
    "9mm",
    12,
    2,
    "ST",
    50,
    300,
    "A sturdy Solo's gun, used as a standard military sidearm in the U.S. and E.C.C.",
  ),

  // ═══ HEAVY AUTOPISTOLS ═══

  budgetarms_auto3: w(
    "budgetarms_auto3",
    "BudgetArms Auto 3",
    "P",
    -1,
    "J",
    "E",
    "3D6",
    "11mm",
    8,
    2,
    "UR",
    50,
    350,
    "It's cheap. It's powerful. It blows up sometimes. What else do you want?",
  ),
  sternmeyer_type35: w(
    "sternmeyer_type35",
    "Sternmeyer Type 35",
    "P",
    0,
    "J",
    "C",
    "3D6",
    "11mm",
    8,
    2,
    "VR",
    50,
    400,
    "Rugged, reliable, with excellent stopping power. A fine E.C.C. product from the United Germanies.",
  ),

  // ═══ VERY HEAVY AUTOPISTOLS ═══

  armalite_44: w(
    "armalite_44",
    "Armalite 44",
    "P",
    0,
    "J",
    "E",
    "4D6+1",
    "12mm",
    8,
    1,
    "ST",
    50,
    450,
    "Designed as an alternate to the 1998 U.S. Army sidearm trials. A solid contender.",
  ),
  colt_amt_2000: w(
    "colt_amt_2000",
    "Colt AMT Model 2000",
    "P",
    0,
    "J",
    "C",
    "4D6+1",
    "12mm",
    8,
    1,
    "VR",
    50,
    500,
    "Standard officer's sidearm for the U.S. Army. Served well in the Central American Wars.",
  ),

  // ═══ LIGHT SUBMACHINEGUNS ═══

  uzi_miniauto_9: w(
    "uzi_miniauto_9",
    "Uzi Miniauto 9",
    "SMG",
    1,
    "J",
    "E",
    "2D6+1",
    "9mm",
    30,
    35,
    "VR",
    150,
    475,
    "Uzi's entry into the 21st century, with rotary electric clip and adjustable trigger.",
  ),
  hk_mp2013: w(
    "hk_mp2013",
    "H&K MP-2013",
    "SMG",
    1,
    "J",
    "C",
    "2D6+3",
    "10mm",
    35,
    32,
    "ST",
    150,
    450,
    "H&K's updating of the MP-5K classic, with compound plastics and built-in silencing.",
  ),
  fed_tech_assault_2: w(
    "fed_tech_assault_2",
    "Fed. Arms Tech Assault II",
    "SMG",
    1,
    "J",
    "C",
    "1D6+1",
    "6mm",
    50,
    25,
    "ST",
    150,
    400,
    "Updated version of the Tech Assault I. Larger clip, better autofire, no melting. Honest.",
  ),

  // ═══ MEDIUM SUBMACHINEGUNS ═══

  arasaka_minami_10: w(
    "arasaka_minami_10",
    "Arasaka Minami 10",
    "SMG",
    0,
    "J",
    "E",
    "2D6+3",
    "10mm",
    40,
    20,
    "VR",
    200,
    500,
    "The standard Arasaka Security weapon, found worldwide. A good, all-round weapon.",
  ),
  hk_mpk9: w(
    "hk_mpk9",
    "H&K MPK-9",
    "SMG",
    1,
    "J",
    "C",
    "2D6+1",
    "9mm",
    35,
    25,
    "ST",
    200,
    520,
    "A light composite submachinegun with integral sights. Used by many Euro Solos.",
  ),

  // ═══ HEAVY SUBMACHINEGUNS ═══

  sternmeyer_smg21: w(
    "sternmeyer_smg21",
    "Sternmeyer SMG 21",
    "SMG",
    -1,
    "L",
    "E",
    "3D6",
    "11mm",
    30,
    15,
    "VR",
    200,
    500,
    "Sternmeyer's best entry in the anti-terrorist category, with wide use on C-SWAT teams and PsychoSquads.",
  ),
  hk_mpk11: w(
    "hk_mpk11",
    "H&K MPK-11",
    "SMG",
    0,
    "L",
    "C",
    "4D6+1",
    "12mm",
    30,
    20,
    "ST",
    200,
    700,
    "Possibly the most used Solo's gun in existence. Can be modified into four different designs.",
  ),
  ingram_mac14: w(
    "ingram_mac14",
    "Ingram MAC 14",
    "SMG",
    -2,
    "L",
    "E",
    "4D6+1",
    "12mm",
    20,
    10,
    "ST",
    200,
    650,
    "Updated MAC-10, with composite body and cylindrical feeding magazine.",
  ),

  // ═══ ASSAULT RIFLES ═══

  militech_ronin: w(
    "militech_ronin",
    "Militech Ronin Light Assault",
    "RIF",
    1,
    "N",
    "C",
    "5D6",
    "5.56mm",
    35,
    30,
    "VR",
    400,
    450,
    "A light, all purpose update, similar to the M-16B.",
  ),
  akr20: w(
    "akr20",
    "AKR-20 Medium Assault",
    "RIF",
    0,
    "N",
    "C",
    "5D6",
    "5.56mm",
    30,
    30,
    "ST",
    400,
    500,
    "A plastic and carbon fiber update of the AKM, distributed throughout the remains of the Soviet Bloc.",
  ),
  fn_ral: w(
    "fn_ral",
    "FN-RAL Heavy Assault Rifle",
    "RIF",
    -1,
    "N",
    "C",
    "6D6+2",
    "7.62mm",
    30,
    30,
    "VR",
    400,
    600,
    "The standard NATO assault weapon for battlefield work. Bullpup design, collapsing stock.",
  ),
  kalishnikov_a80: w(
    "kalishnikov_a80",
    "Kalishnikov A-80 Hvy. Rifle",
    "RIF",
    -1,
    "N",
    "E",
    "6D6+2",
    "7.62mm",
    35,
    25,
    "ST",
    400,
    550,
    "Another Soviet retread, with improved sighting and lightened with composites.",
  ),

  // ═══ SHOTGUNS ═══

  arasaka_shot12: w(
    "arasaka_shot12",
    "Arasaka Rapid Assault 12",
    "SHT",
    -1,
    "N",
    "C",
    "4D6",
    "00",
    20,
    10,
    "ST",
    50,
    900,
    "A high powered auto-shotgun with lethal firepower. Used by Arasaka worldwide.",
  ),
  sternmeyer_stakeout: w(
    "sternmeyer_stakeout",
    "Sternmeyer Stakeout 10",
    "SHT",
    -2,
    "N",
    "R",
    "4D6",
    "00",
    10,
    2,
    "ST",
    50,
    450,
    "Light duty stakeout shotgun, used by city police departments.",
  ),

  // ═══ HEAVY WEAPONS ═══

  barrett_arasaka_20mm: w(
    "barrett_arasaka_20mm",
    "Barrett-Arasaka Light 20mm",
    "HVY",
    0,
    "N",
    "R",
    "4D10 AP",
    "20mm",
    10,
    1,
    "VR",
    450,
    2000,
    "The cyberpsycho hunter's favorite. Almost 2 meters long, fires depleted uranium shells at supersonic speeds.",
  ),
  scorpion_16: w(
    "scorpion_16",
    "Scorpion 16 Missile Launcher",
    "HVY",
    -1,
    "N",
    "R",
    "7D10",
    "missile",
    1,
    1,
    "VR",
    1000,
    3000,
    "Third generation Stinger missile launcher. Shoulder arm fires one missile.",
  ),
  militech_rpg_a: w(
    "militech_rpg_a",
    "Militech Arms RPG-A",
    "HVY",
    -2,
    "N",
    "R",
    "6D10",
    "rocket",
    1,
    1,
    "VR",
    750,
    1500,
    "Shoulder-mounted, rocket-powered grenade launcher. Heavily used in Central American conflicts.",
  ),
  // Grenades, explosives & mines — self-deployable ammo, different rules. Will handle separately.
  // grenade: w("grenade", "Grenade", "HVY", 0, "P", "P", "varies", "grenade", 1, 1, "VR", 0, 30, "..."),
  // c6_plastic_explosive: w("c6_plastic_explosive", 'C-6 "Flatfire" Plastic Explosive', "HVY", 0, "P", "P", "8D10/kg", "explosive", 1, 1, "VR", 0, 100, "..."),
  // mine: w("mine", "Mine (all types)", "HVY", 0, "J", "P", "4D10", "explosive", 1, 1, "VR", 0, 350, "..."),

  ka_f253_flamethrower: w(
    "ka_f253_flamethrower",
    "Kenshiri Adachi F-253 Flamethrower",
    "HVY",
    -2,
    "N",
    "R",
    "2D10",
    "napalm",
    10,
    1,
    "ST",
    50,
    1500,
    "Liquified napalm sprayer. Back mounted and bulky. Does extra damage following initial hit.",
  ),

  // ═══ EXOTICS ═══

  techtronica_15: w(
    "techtronica_15",
    "Techtronica 15 Microwaver",
    "P",
    0,
    "J",
    "P",
    "1D6",
    "mwave",
    10,
    2,
    "VR",
    20,
    400,
    "Flashlight sized microwave projector. See FNFF for microwave damage rules.",
  ),
  militech_lasercannon: w(
    "militech_lasercannon",
    "Militech Electronics LaserCannon",
    "RIF",
    0,
    "N",
    "R",
    "1-5D6",
    "battery",
    10,
    2,
    "UR",
    200,
    8000,
    "Milspec laser cannon, rarely seen. See FNFF for details.",
  ),
  avante_needlegun: w(
    "avante_needlegun",
    "Avante P-1135 Needlegun",
    "P",
    0,
    "P",
    "P",
    "drugs",
    "needle",
    15,
    2,
    "ST",
    40,
    200,
    "Lightweight, plastic, compressed air powered. Can be doped with drugs, poison.",
  ),
  enertex_power_squirt: w(
    "enertex_power_squirt",
    "Enertex AKM Power Squirt",
    "P",
    -2,
    "J",
    "C",
    "drugs",
    "drug",
    50,
    1,
    "VR",
    10,
    15,
    "A powered squirtgun. Can fire acid, drugs, poison.",
  ),
  nelspot_wombat: w(
    "nelspot_wombat",
    'Nelspot "Wombat" Airpistol',
    "P",
    -1,
    "J",
    "C",
    "drugs",
    "paint",
    20,
    2,
    "UR",
    40,
    200,
    "Paintball gun from hell. Can fire acid, paint, drugs, poison.",
  ),
  miltech_taser: w(
    "miltech_taser",
    "Miltech Electronics Taser",
    "P",
    -1,
    "J",
    "C",
    "stun",
    "charge",
    10,
    1,
    "ST",
    10,
    60,
    "Zap. About the size of a small hand flashlight.",
  ),
  eagletech_tomcat: w(
    "eagletech_tomcat",
    'EagleTech "Tomcat" Compound Bow',
    "EX",
    0,
    "N",
    "C",
    "4D6",
    "arrow",
    12,
    1,
    "VR",
    150,
    150,
    "Gyrobalanced, stabilized compound bow. Silent & deadly.",
  ),
  eagletech_stryker: w(
    "eagletech_stryker",
    'EagleTech "Stryker" Crossbow',
    "EX",
    -1,
    "N",
    "C",
    "3D6+3",
    "bolt",
    12,
    1,
    "VR",
    50,
    220,
    "Plastic and bimetal crossbow. Silent and deadly, and you usually get your ammo back.",
  ),

  // ═══ MELEE WEAPONS — Cyberpunk 2020 ═══

  kendachi_monoknife: w(
    "kendachi_monoknife",
    "Kendachi Monoknife\u00AE",
    "melee",
    1,
    "P",
    "P",
    "2D6",
    "",
    0,
    0,
    "VR",
    1,
    200,
    'Mono-sectional crystal blade. Incredibly sharp. In the Japanese "tanto" style.',
  ),
  kendachi_monokatana: w(
    "kendachi_monokatana",
    "Kendachi MonoKatana\u00AE",
    "melee",
    1,
    "N",
    "R",
    "4D6",
    "",
    0,
    0,
    "VR",
    1,
    600,
    "Sword length version of monoblade. Resembles a hightech katana with a milky, nearly transparent blade.",
  ),
  spm1_battleglove: w(
    "spm1_battleglove",
    "SPM-1 Battleglove\u2122",
    "melee",
    -2,
    "N",
    "P",
    "3D6/2D6",
    "",
    0,
    0,
    "VR",
    1,
    900,
    "Large gauntlet covering hand and forearm. 3D6 crush, 2D6 punch damage. Three standard cyberarm option spaces.",
  ),

  // ═══ MELEE WEAPONS — Generic ═══

  club: w(
    "club",
    "Club",
    "melee",
    0,
    "L",
    "C",
    "1D6",
    "",
    0,
    0,
    "VR",
    1,
    0,
    "A blunt instrument. Free.",
  ),
  knife: w(
    "knife",
    "Knife",
    "melee",
    0,
    "P",
    "C",
    "1D6",
    "",
    0,
    0,
    "VR",
    1,
    20,
    "Standard knife.",
  ),
  sword: w(
    "sword",
    "Sword",
    "melee",
    0,
    "N",
    "C",
    "2D6+2",
    "",
    0,
    0,
    "VR",
    1,
    200,
    "Standard sword.",
  ),
  axe: w(
    "axe",
    "Axe",
    "melee",
    -1,
    "N",
    "C",
    "2D6+3",
    "",
    0,
    0,
    "VR",
    1,
    20,
    "Standard axe.",
  ),
  nunchaku: w(
    "nunchaku",
    "Nunchaku/Tonfa",
    "melee",
    0,
    "L",
    "C",
    "3D6",
    "",
    0,
    0,
    "VR",
    1,
    15,
    "Martial arts striking weapon.",
  ),
  naginata: w(
    "naginata",
    "Naginata",
    "melee",
    0,
    "N",
    "P",
    "3D6",
    "",
    0,
    0,
    "VR",
    2,
    100,
    "Japanese polearm weapon.",
  ),
  shuriken: w(
    "shuriken",
    "Shuriken",
    "melee",
    0,
    "P",
    "C",
    "1D6/3",
    "",
    0,
    0,
    "VR",
    0,
    3,
    "Throwing star. Range depends on thrower.",
  ),
  switchblade: w(
    "switchblade",
    "Switchblade",
    "melee",
    0,
    "P",
    "C",
    "1D6/2",
    "",
    0,
    0,
    "VR",
    1,
    15,
    "Concealed spring-loaded blade.",
  ),
  brass_knuckles: w(
    "brass_knuckles",
    "Brass Knuckles",
    "melee",
    0,
    "P",
    "C",
    "1D6+2",
    "",
    0,
    0,
    "VR",
    1,
    10,
    "Reinforced fist weapon.",
  ),
  sledgehammer: w(
    "sledgehammer",
    "Sledgehammer",
    "melee",
    -1,
    "N",
    "C",
    "4D6",
    "",
    0,
    0,
    "VR",
    1,
    20,
    "Heavy two-handed impact weapon.",
  ),
  chainsaw: w(
    "chainsaw",
    "Chainsaw",
    "melee",
    -3,
    "N",
    "C",
    "4D6",
    "",
    0,
    0,
    "VR",
    2,
    80,
    "Power tool repurposed for violence.",
  ),

  // ═══ OLD GUNS — Pre-2000 weapons still found on the Street ═══
  // Prices approximate (Referee sets final price)

  sw_combat_magnum: w(
    "sw_combat_magnum",
    "S&W Combat Magnum",
    "P",
    1,
    "J",
    "C",
    "2D6+3",
    ".357",
    6,
    2,
    "VR",
    50,
    125,
    'Designed for US Border Patrol use. "Small frame" and reliable action make it a best seller.',
  ),
  llama_commanche: w(
    "llama_commanche",
    "Llama Commanche",
    "P",
    0,
    "J",
    "C",
    "4D6",
    ".44",
    6,
    1,
    "ST",
    50,
    225,
    "An excellent .44 revolver, used in home defense and police work. Long barrel makes it hard to conceal.",
  ),
  colt_peacemaker: w(
    "colt_peacemaker",
    'Colt .45 "Peacemaker"',
    "P",
    0,
    "J",
    "R",
    "2D6+2",
    ".45",
    6,
    1,
    "VR",
    50,
    150,
    'The gun "that won the West". Single action, must be cocked before firing.',
  ),
  colt_detective: w(
    "colt_detective",
    "Colt .38 Detective",
    "P",
    1,
    "J",
    "C",
    "1D6+2",
    ".38",
    6,
    1,
    "VR",
    50,
    100,
    'The most commonplace police weapon for many years, including the "Chief\'s Special".',
  ),
  cop_357: w(
    "cop_357",
    "C.O.P. .357 Derringer",
    "P",
    0,
    "P",
    "C",
    "2D6+3",
    ".357",
    4,
    2,
    "VR",
    50,
    75,
    'Designed as a "holdout" for law enforcement. Unique revolving firing pin. Small size makes it easily hidden.',
  ),
  uzi: w(
    "uzi",
    "UZI",
    "SMG",
    2,
    "J",
    "C",
    "2D6+1",
    "9mm",
    30,
    20,
    "VR",
    150,
    250,
    "The classic Israeli export weapon. Used worldwide by security forces, police and drug dealers.",
  ),
  vz61_skorpion: w(
    "vz61_skorpion",
    "Vz61 Skorpion",
    "SMG",
    2,
    "J",
    "P",
    "1D6",
    ".25",
    20,
    25,
    "VR",
    150,
    200,
    "The world's smallest military SMG. Easily silenced, fits in a shoulder holster.",
  ),
  ingram_mac10: w(
    "ingram_mac10",
    "Ingram MAC 10",
    "SMG",
    -1,
    "J",
    "C",
    "2D6+2",
    ".45",
    30,
    10,
    "UR",
    150,
    200,
    "A very small SMG used by covert units and terrorists. Easily silenced, hard to control on full auto. Note: original RoF is 5.",
  ),
  hk_mp5: w(
    "hk_mp5",
    "H&K MP5",
    "SMG",
    1,
    "L",
    "C",
    "2D6+1",
    "9mm",
    30,
    20,
    "ST",
    150,
    300,
    "Two examples of the H&K family of interchangeable SMGs. The MP5K has built in silencer.",
  ),
  thompson_m1: w(
    "thompson_m1",
    "Thompson M1",
    "SMG",
    2,
    "N",
    "C",
    "2D6+2",
    ".45",
    30,
    20,
    "VR",
    150,
    250,
    "Standard US military SMG during WWII. Rugged, reliable and easy to use.",
  ),
  fn_fal: w(
    "fn_fal",
    "FN-FAL",
    "RIF",
    0,
    "N",
    "E",
    "6D6+2",
    "7.62mm",
    20,
    21,
    "VR",
    400,
    350,
    "Standard NATO rifle. A very deadly assault weapon; durable and handles well.",
  ),
  ak47: w(
    "ak47",
    "AK-47",
    "RIF",
    0,
    "N",
    "E",
    "5D6",
    "7.62x39",
    30,
    30,
    "VR",
    400,
    250,
    "Standard Soviet military rifle. Reliable, but difficult to control. The most well known weapon of its type.",
  ),
  m16a2: w(
    "m16a2",
    "M-16A2",
    "RIF",
    2,
    "N",
    "C",
    "4D6",
    "5.56mm",
    30,
    25,
    "UR",
    400,
    250,
    "Standard US military rifle since the 1960's. High accuracy and staggering ROF, but cantankerous and unreliable.",
  ),
  steyr_aug: w(
    "steyr_aug",
    "Steyr AUG",
    "RIF",
    2,
    "N",
    "C",
    "4D6",
    "5.56mm",
    30,
    20,
    "VR",
    400,
    300,
    "A bullpup configured rifle using high tech plastics and aluminium. Great accuracy and rugged plastic construction.",
  ),
  winchester_m70: w(
    "winchester_m70",
    "Winchester M70",
    "RIF",
    3,
    "N",
    "C",
    "5D6+1",
    "30-06",
    5,
    1,
    "VR",
    400,
    200,
    "A basic scoped hunting rifle, used to hunt deer.",
  ),
  caws: w(
    "caws",
    "CAWS",
    "SHT",
    0,
    "N",
    "R",
    "4D6",
    "00",
    10,
    10,
    "ST",
    50,
    500,
    "Close Assault Weapon System. Designed for house to house work, crowd suppression. Scope is built in.",
  ),
};

export { AVAILABILITY_LABELS } from "@scripts/catalog-common";
